### ISSUE TITLE
Non-normalized data

### ISSUE THREAD

**Issue by fitnr** [Bellspringsteen/other.nyc#1]
As far as I can tell, the maps currently show a color scale based on the absolute number of officers in the ZIP (see [line 64 of WhereDoesNYPDLive.html](WhereDoesNYPDLive.html#L64)).

This is misleading. Since ZIP Codes vary considerably in land size and population density, the map is emphazing those aspects of the data, rather than the concentration or distribution of officers' home addresses.  I suggest either normalizing by the population (population proportion of officers), or refactoring to a dot density map, with one dot per officer). [Here's a quick version as a dot density map](https://fitnr.carto.com/viz/aa7e76e0-9863-11e6-914d-0ecd1babdde5/public_map) and [as a proportion of the population](https://fitnr.carto.com/viz/91587a4c-9865-11e6-a662-0e3ff518bd15/public_map)

(Note that the second map and the current map are really similar. The reason is that ZIP codes generally have the same magnitude of population, so you're getting something close to normalization by population for free just because of an artifact of how the lines are drawn)

**Comment by Bellspringsteen** [comment]
Hello, 

Thanks for the feedback. I was just looking to show where the officers live. But correcting by population is interesting as is the dot density.
