### ISSUE TITLE
Officer's home precinct data

### ISSUE THREAD

**Issue by ebrelsford** [Bellspringsteen/other.nyc#2]
Is [NYPDFoilOfficerHomeZipData](https://github.com/Bellspringsteen/other.nyc/blob/master/NYCGOV/NYPD/NypdOfficersHomeZip/data/NYPDFoilOfficerHomeZipData.csv) all the data you received from the NYPD?

You requested the officer's home precinct, too, and as has been pointed out in the comments of your [blog post](http://blog.labsbell.com/blog/NYPDHomeZip) there's nothing stopping officers from living in the same zip code as the one their precinct is in, they just can't live in the same precinct. As it stands the "living illegally" bit in the second map seems pretty misleading.

**Comment by Bellspringsteen** [comment]
Hello. 

Yes this is all I received. As for the living illegally. I have to find some time to look at this. As far as i can see, the vast majority of precincts don't overlap zips. So if a person lives in the same zip, there is a strong chance they live in the same precinct. But I have to crunch the data on this. Or you could? Let me know, happy to update if I find more data. Do you know of any shapefiles or descriptions of precinct boundaries?

**Comment by ebrelsford** [comment]
I don't think it requires much data crunching. As far as I can see, the only time [precinct](https://data.cityofnewyork.us/Public-Safety/Police-Precincts/78dh-3ptz) and zip code boundaries are at all similar is at the edge of a borough. There are definitely some zip codes that are entirely within their precinct, but not many.

For example, (black: zip codes, red: precincts):

![selection_003](https://cloud.githubusercontent.com/assets/375002/19812482/aec529e8-9d03-11e6-869c-e592ee88861c.png)

**Comment by Bellspringsteen** [comment]
Cool, thanks for sharing. I will find some time and update
